# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  component_name: user 
  
resources:
  repositories:
    - repository: templates
      type: git
      name: azd-ci-templates
      
steps:


#- template: codecheck.yml@templates

- task: Docker@2
  inputs:
    containerRegistry: 'Docker-Hub'
    repository: 'rkalluru/d51-user'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: '1.0.$(Build.BuildId)'

- task: UniversalPackages@0
  inputs:
    command: 'publish'
    publishDirectory: '$(Build.ArtifactStagingDirectory)'
    feedsToUsePublish: 'internal'
    vstsFeedPublish: 'ce99914a-0f7d-4c46-9ccc-e4d025115ea9/aceb203d-03c1-40f9-b6e1-2c1450fcebd6'
    vstsFeedPackagePublish: 'user'
    versionOption: 'custom'
    versionPublish: '1.0.$(Build.BuildId)'

- script: |
    npm install 
    mkdir publish 
    cp -r node_modules package.json server.js publish
  displayName: Install NodeJS Dependencies
  
- script: |
    cp -r node_modules package.json server.js publish
  displayName: Prepare Arrtifacts
  
- task: UniversalPackages@0
  inputs:
    command: 'publish'
    publishDirectory: '$(Build.SourcesDirectory)/publish'
    feedsToUsePublish: 'internal'
    vstsFeedPublish: 'ce99914a-0f7d-4c46-9ccc-e4d025115ea9/f0174cff-2623-4600-a29f-0eb8a06b0a0c'
    vstsFeedPackagePublish: 'user'
    versionOption: 'patch'
    packagePublishDescription: 'RoboShop User'